import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Landingpage/Header";
import Footer from "@/components/Landingpage/Footer";
import Login from "@/components/Landingpage/Login";
import Storewrap from "@/components/Landingpage/Storewrap";
import Resiterwrapper from "@/components/Landingpage/Registerwrapper";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Storewrap>
        <Header />
     <Resiterwrapper />

        {children}
        <Footer />
        </Storewrap>
      
      </body>
    </html>
  );
}
